/**
 * Banque d'icônes ZeroGaspy — Brand Bible §06 (famille Phosphor).
 *
 * Règle : les icônes UI produit passent par `BrandIcon` + ces clés sémantiques.
 * Ne pas mélanger Ionicons / SF Symbols pour les nouveaux écrans DS v2.
 */
import {
  AppleLogo,
  ArrowSquareOut,
  ArrowsClockwise,
  Barcode,
  Bell,
  Bookmark,
  BookOpen,
  BracketsCurly,
  Cake,
  CalendarBlank,
  Camera,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChartBar,
  Check,
  CheckCircle,
  Clock,
  Cloud,
  CloudArrowUp,
  CloudCheck,
  Coffee,
  CookingPot,
  Cube,
  CurrencyEur,
  DeviceMobile,
  Envelope,
  Eye,
  EyeSlash,
  FileText,
  Flame,
  Folder,
  Funnel,
  Gear,
  Gift,
  Globe,
  Hash,
  House,
  Image,
  Images,
  Info,
  Key,
  Leaf,
  Lightbulb,
  Lightning,
  ListBullets,
  Lock,
  MagnifyingGlass,
  Minus,
  MinusCircle,
  Package,
  PencilSimple,
  Plus,
  PlusCircle,
  Receipt,
  Scan,
  Scales,
  Seal,
  ShareNetwork,
  Shield,
  ShieldCheck,
  SignOut,
  SlidersHorizontal,
  Snowflake,
  Sparkle,
  SquaresFour,
  Star,
  Sun,
  Table,
  Trash,
  TrendDown,
  TrendUp,
  Trophy,
  TwitterLogo,
  User,
  UserPlus,
  Users,
  Wallet,
  Warning,
  WarningCircle,
  Wine,
  XCircle,
  ShoppingCart,
} from 'phosphor-react-native';
import type { Icon } from 'phosphor-react-native';

export const BRAND_ICONS = {
  add: Plus,
  apple: AppleLogo,
  barcode: Barcode,
  bell: Bell,
  book: BookOpen,
  bookmark: Bookmark,
  breakfast: Sun,
  cake: Cake,
  calendar: CalendarBlank,
  camera: Camera,
  chart: ChartBar,
  check: Check,
  checkCircle: CheckCircle,
  chevronDown: CaretDown,
  chevronLeft: CaretLeft,
  chevronRight: CaretRight,
  chevronUp: CaretUp,
  clock: Clock,
  close: XCircle,
  cloud: Cloud,
  cloudCheck: CloudCheck,
  cloudUpload: CloudArrowUp,
  code: BracketsCurly,
  coffee: Coffee,
  cook: CookingPot,
  cube: Cube,
  drink: Wine,
  cart: ShoppingCart,
  edit: PencilSimple,
  envelope: Envelope,
  euro: CurrencyEur,
  externalLink: ArrowSquareOut,
  eye: Eye,
  eyeSlash: EyeSlash,
  file: FileText,
  flame: Flame,
  food: Package,
  folder: Folder,
  filter: Funnel,
  fridge: Snowflake,
  gear: Gear,
  gift: Gift,
  globe: Globe,
  grid: SquaresFour,
  hash: Hash,
  home: House,
  image: Image,
  images: Images,
  info: Info,
  key: Key,
  leaf: Leaf,
  lightbulb: Lightbulb,
  lightning: Lightning,
  list: ListBullets,
  lock: Lock,
  minus: Minus,
  minusCircle: MinusCircle,
  mobile: DeviceMobile,
  plus: Plus,
  plusCircle: PlusCircle,
  receipt: Receipt,
  scan: Scan,
  shield: Shield,
  shieldCheck: ShieldCheck,
  scales: Scales,
  seal: Seal,
  search: MagnifyingGlass,
  share: ShareNetwork,
  signOut: SignOut,
  sliders: SlidersHorizontal,
  sparkle: Sparkle,
  star: Star,
  sun: Sun,
  sync: ArrowsClockwise,
  table: Table,
  trash: Trash,
  trendDown: TrendDown,
  trendUp: TrendUp,
  trophy: Trophy,
  twitter: TwitterLogo,
  user: User,
  userPlus: UserPlus,
  users: Users,
  wallet: Wallet,
  warning: Warning,
  warningCircle: WarningCircle,
} as const satisfies Record<string, Icon>;

export type BrandIconName = keyof typeof BRAND_ICONS;

/** Icônes Phosphor par catégorie de recette. */
export const RECIPE_CATEGORY_ICONS = {
  'petit-déjeuner': 'breakfast',
  plat: 'cook',
  entrée: 'leaf',
  dessert: 'cake',
  snack: 'coffee',
  boisson: 'drink',
} as const satisfies Record<string, BrandIconName>;

/** Icônes Phosphor par défi hebdomadaire (remplace SF Symbols). */
export const CHALLENGE_ICONS = {
  zero_waste_week: 'sync',
  save_20: 'shield',
  save_5: 'leaf',
  add_15: 'food',
  add_5: 'star',
  recipes_10: 'cook',
  recipes_3: 'book',
  daily_5: 'calendar',
  daily_7: 'flame',
  consume_10: 'cook',
  consume_25: 'lightning',
  add_varied_3: 'grid',
  streak_5: 'flame',
  no_throw_3: 'leaf',
  all_actions: 'trophy',
  add_varied_5: 'folder',
  recipes_15: 'cook',
  no_throw_7: 'seal',
  consume_5: 'cook',
} as const satisfies Record<string, BrandIconName>;

export const CHALLENGE_ICON_DEFAULT: BrandIconName = 'star';

